spring.main.banner-mode: log
spring.profiles.include:
  - datasource
  - common

spring.profiles.active: dev


---
spring:
  profiles: dev

spring.application.name: 商品-开发

---
spring:
  profiles: test

spring.application.name: 商品-测试

---
spring:
  profiles: awstest

spring.application.name: 商品-测试

---
spring:
  profiles: prod


spring.application.name: 商品
