mail.send.from: devadmin@realme.net
aws.sns.key: AKIAJ56HOXK4BGE7I3OA
aws.sns.secret: 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

spring.mail:
  host: smtp.realme.net
  port: 25
  username: devadmin@realme.net
  password: dk7^dy3-Kmt4G
  protocol: smtp
  test-connection: false
  properties.mail.smtp.connectiontimeout: 5000
  properties.mail.smtp.timeout: 3000
  properties.mail.smtp.writetimeout: 5000

#dubbo default configuration
dubbo.protocol.port: 20880
dubbo.protocol.dispatcher: all

dubbo.provider.threads: 1000
dubbo.provider.threadpool: fixed
dubbo.provider.timeout: 1000
dubbo.provider.retries: 1

---
spring:
  profiles: dev

dubbo.provider.threads: 20
dubbo.zk.address: 172.16.44.159:2181,172.16.44.160:2181,172.16.44.161:2181

spring.redis:
  cluster:
    max-redirects: 3
    nodes: 172.16.44.159:6379,172.16.44.160:6379,172.16.44.161:6379,172.16.44.159:6380,172.16.44.160:6380,172.16.44.161:6380
  database: 0
  timeout: 2000ms

---
spring:
  profiles: test

dubbo.provider.threads: 20
dubbo.zk.address: 172.16.44.184:2181,172.16.44.185:2181,172.16.44.186:2181

spring.redis:
  cluster:
    max-redirects: 3
    nodes: 172.16.44.164:6379,172.16.44.164:6380,172.16.44.164:6381,172.16.44.164:7379,172.16.44.164:7380,172.16.44.164:7381
  database: 0
  timeout: 2000ms

---
spring:
  profiles: awstest


dubbo.zk.address: 172.25.254.95:2181,172.25.254.95:2182,172.25.254.95:2183

spring.redis:
  cluster:
    max-redirects: 3
    nodes:
#      - realme-test-rds-0001-001.aw2mps.0001.aps1.cache.amazonaws.com:6379
#      - realme-test-rds-0002-001.aw2mps.0001.aps1.cache.amazonaws.com:6379
#      - realme-test-rds-0003-001.aw2mps.0001.aps1.cache.amazonaws.com:6379
      - redis-prod-redis-01.aw2mps.clustercfg.aps1.cache.amazonaws.com:6379
  database: 0
  timeout: 2000ms

#aws ses service
spring.mail:
  host: email-smtp.us-east-1.amazonaws.com
  username: AKIAIZWX6LES54RZXCQA
  password: AiVkTzxOAkAydYBXLJWP2FwvoXebH3Bg19TnoJ0MqV2o
  properties.mail.transport.protocol: smtp
  properties.mail.smtp.port: 25
  properties.mail.smtp.auth: true
  properties.mail.smtp.starttls.enable: true
  properties.mail.smtp.starttls.required: true

---
spring:
  profiles: prod


dubbo.zk.address: 172.25.4.20:2181,172.25.4.21:2181,172.25.5.20:2181

spring.redis:
  cluster:
    max-redirects: 3
    nodes:
#      - redis-prod-redis-01-0001-001.aw2mps.0001.aps1.cache.amazonaws.com:6379
#      - redis-prod-redis-01-0001-002.aw2mps.0001.aps1.cache.amazonaws.com:6379
#      - redis-prod-redis-01-0002-001.aw2mps.0001.aps1.cache.amazonaws.com:6379
#      - redis-prod-redis-01-0002-002.aw2mps.0001.aps1.cache.amazonaws.com:6379
#      - redis-prod-redis-01-0003-001.aw2mps.0001.aps1.cache.amazonaws.com:6379
#      - redis-prod-redis-01-0003-002.aw2mps.0001.aps1.cache.amazonaws.com:6379
      - redis-prod-redis-01.aw2mps.clustercfg.aps1.cache.amazonaws.com:6379
  database: 0
  timeout: 2000ms

