#aws s3 configuration
amazon.access.id: AKIAJLTD6QRAEJFR6GDA
amazon.secret.key: 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
amazon.s3.bucket.name: realme-oms-test

#dubbo default configuration
dubbo.provider.threads: 200
---
spring:
  profiles: dev

dubbo.provider.threads: 20
cms.page.save.dir: /data/workdir/oms/pages
shopping.page.save.dir: /data/workdir/oms/shopping
page.cdn.url.prefix: https://dev-static.myoas.net
s3.cdn.url.prefix: https://image01.myoas.net
site.url.prefix: https://dev.myoas.net
shopping.site.url.prefix: https://dev-buy.myoas.net
shopping.err_page.save.dir: /data/workdir/oms/shopping
shopping.err_page.file.name: offline.html

dubbo.zk.address: 172.16.44.159:2181,172.16.44.160:2181,172.16.44.161:2181

spring.redis:
  cluster:
    max-redirects: 3
    nodes: 172.16.44.159:6379,172.16.44.160:6379,172.16.44.161:6379,172.16.44.159:6380,172.16.44.160:6380,172.16.44.161:6380
  database: 0
  timeout: 2000ms



---
spring:
  profiles: test,test1

cms.page.save.dir: /data/workdir/oms/pages
shopping.page.save.dir: /data/workdir/oms/shopping
page.cdn.url.prefix: https://test1-static.myoas.net
s3.cdn.url.prefix: https://image01.myoas.net
site.url.prefix: https://test1.myoas.net
shopping.site.url.prefix: https://test1-buy.myoas.net
shopping.err_page.save.dir: /data/workdir/oms/shopping
shopping.err_page.file.name: offline.html

dubbo.zk.address: 172.16.44.184:2181,172.16.44.185:2181,172.16.44.186:2181

spring.redis:
  cluster:
    max-redirects: 3
    nodes: 172.16.44.164:6379,172.16.44.164:6380,172.16.44.164:6381,172.16.44.164:7379,172.16.44.164:7380,172.16.44.164:7381
  database: 0
  timeout: 2000ms



---
spring:
  profiles: test2

page.cdn.url.prefix: https://test2-static.myoas.net
site.url.prefix: https://test2.myoas.net
shopping.site.url.prefix: https://test2-buy.myoas.net
shopping.err_page.save.dir: /data/workdir/oms/shopping
shopping.err_page.file.name: offline.html


---
spring:
  profiles: awstest

cms.page.save.dir: /data/workdir/oms/pages
shopping.page.save.dir: /data/workdir/oms/shopping
page.cdn.url.prefix: https://static.myoas.net
s3.cdn.url.prefix: https://image01.realme.net
site.url.prefix: https://pre-www.realme.com
shopping.site.url.prefix: https://pre-buy.realme.com
shopping.err_page.save.dir: /data/workdir/oms/shopping
shopping.err_page.file.name: offline.html

dubbo.zk.address: 172.25.254.95:2181,172.25.254.95:2182,172.25.254.95:2183

spring.redis:
  cluster:
    max-redirects: 3
    nodes:
#      - realme-test-rds-0001-001.aw2mps.0001.aps1.cache.amazonaws.com:6379
#      - realme-test-rds-0002-001.aw2mps.0001.aps1.cache.amazonaws.com:6379
#      - realme-test-rds-0003-001.aw2mps.0001.aps1.cache.amazonaws.com:6379
      - realme-test-rds.aw2mps.clustercfg.aps1.cache.amazonaws.com:6379
  database: 0
  timeout: 2000ms

#aws s3 configuration
amazon.access.id: AKIAIU5QRTZ756EZDPBQ
amazon.secret.key: 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
amazon.s3.bucket.name: realme-upload

---
spring:
  profiles: prod


cms.page.save.dir: /data/workdir/oms/pages
shopping.page.save.dir: /data/workdir/oms/shopping
page.cdn.url.prefix: https://static.realme.net
s3.cdn.url.prefix: https://image01.realme.net
site.url.prefix: https://www.realme.com
shopping.site.url.prefix: https://buy.realme.com
shopping.err_page.save.dir: /data/workdir/oms/shopping
shopping.err_page.file.name: offline.html

# pre zk
dubbo.zk.address: 172.25.254.95:2181,172.25.254.95:2182,172.25.254.95:2183
# prod dubbo.zk.address: 172.25.4.20:2181,172.25.4.21:2181,172.25.5.20:2181

spring.redis:
  cluster:
    max-redirects: 3
    nodes:
      - redis-prod-redis-01.aw2mps.clustercfg.aps1.cache.amazonaws.com:6379
  database: 0
  timeout: 2000ms

#aws s3 configuration
amazon.access.id: AKIAIU5QRTZ756EZDPBQ
amazon.secret.key: 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
amazon.s3.bucket.name: realme-upload