dubbo.protocol.port: 20883
dubbo.provider.threads: 200

---
spring:
  profiles: dev

dubbo.provider.threads: 10
dubbo.zk.address: 172.16.44.159:2181,172.16.44.160:2181,172.16.44.161:2181

spring.redis:
  cluster:
    max-redirects: 3
    nodes: 172.16.44.159:6379,172.16.44.160:6379,172.16.44.161:6379,172.16.44.159:6380,172.16.44.160:6380,172.16.44.161:6380
  database: 0
  timeout: 2000ms

address:
  host: 'http://openaccount.ucnewtest.wanyol.com'
  appKey: 'VVNiWZJAhu6nX7YUaSJcTu'
  appSecret: '8l1IMgH+Z/ffMLwt/+994w=='
  maxCount: 10
aws.subscribe.topic.prefix: dev_
---
spring:
  profiles: test

dubbo.provider.threads: 10
dubbo.zk.address: 172.16.44.184:2181,172.16.44.185:2181,172.16.44.186:2181

spring.redis:
  cluster:
    max-redirects: 3
    nodes: 172.16.44.164:6379,172.16.44.164:6380,172.16.44.164:6381,172.16.44.164:7379,172.16.44.164:7380,172.16.44.164:7381
  database: 0
  timeout: 2000ms

address:
  host: 'http://openaccount.ucnewtest.wanyol.com'
  appKey: 'VVNiWZJAhu6nX7YUaSJcTu'
  appSecret: '8l1IMgH+Z/ffMLwt/+994w=='
  maxCount: 10
aws.subscribe.topic.prefix: test_
---
spring:
  profiles: awstest


dubbo.zk.address: 172.25.254.95:2181,172.25.254.95:2182,172.25.254.95:2183

spring.redis:
  cluster:
    max-redirects: 3
    nodes:
      - redis-prod-redis-01.aw2mps.clustercfg.aps1.cache.amazonaws.com:6379
  database: 0
  timeout: 2000ms
  
address:
  host: 'https://igwf.uc.oppomobile.com'
  appKey: 'VVNiWZJAhu6nX7YUaSJcTu'
  appSecret: '8l1IMgH+Z/ffMLwt/+994w=='
  maxCount: 10
aws.subscribe.topic.prefix: awstest_
---
spring:
  profiles: prod

dubbo.zk.address: 172.25.4.20:2181,172.25.4.21:2181,172.25.5.20:2181

spring.redis:
  cluster:
    max-redirects: 3
    nodes:
      - redis-prod-redis-01.aw2mps.clustercfg.aps1.cache.amazonaws.com:6379
  database: 0
  timeout: 2000ms

address:
  host: 'https://igwf.uc.oppomobile.com'
  appKey: 'VVNiWZJAhu6nX7YUaSJcTu'
  appSecret: '8l1IMgH+Z/ffMLwt/+994w=='
  maxCount: 10
aws.subscribe.topic.prefix: prod_